world_model:
  name: dummy
  checkpoint_path: null
  params:
    num_pred_frames: 5

policy:
  name: dp
  checkpoint_path: null
  params: {}

reward_model:
  name: dummy
  params: {}

scheduler:
  chunk_size: 15

max_steps: 50

train_params:
  learning_rate: 3.0e-4
  num_epochs: 100
  batch_size: 32
